### ISSUE TITLE
One True Path blog post under Resources doesn't seem to exist

### ISSUE THREAD

**Issue by carlyrossi** [learn-co-curriculum/phase-0-navigating-files-in-bash#1]
The One True Path blog post under Resources doesn't seem to exist -- when clicking on that resource, which navigates to http://blog.seldomatt.com/blog/2012/10/08/bash-and-the-one-true-path/, the following populates: 
![Screen Shot 2021-11-13 at 2 59 24 PM](https://user-images.githubusercontent.com/60304350/141661464-1d662469-f336-4b82-8e29-9291fce34807.png)
I'd wager the blog itself no longer exists as navigating to  http://blog.seldomatt.com/ has the same error...and stopped being attributed to the author in 2018. The article doesn't seem to have been carried over to the author's current blog, which is https://blog.buoydevelopment.com/ based on the link on Matthew Salerno's GitHub profile.

**Comment by lizbur10** [comment]
Hi @carlyrossi ! Thanks for bringing this to our attention! The link has been removed. Note that you may not see the change reflected in your Canvas page for this lesson but it will be in place for students moving forward.

Thanks for contributing to the Flatiron School curriculum. 💙
