### ISSUE TITLE
CLI ordering

### ISSUE THREAD

**Issue by mikeship04** [learn-co-curriculum/phase-0-navigating-files-in-bash#4]
### Canvas Link

https://learning.flatironschool.com/courses/5506

### Concern

Working with files and directories prior to Organizing your work.

### Additional Context

This is less an actual bug vs being exceptionally confusing for no particular reason.  In following the video tutorial in the section for organizing your work (which comes after Working with files and directories) a couple of pain points become clear, namely, working in a virtual environment vs. your desktop or C: drive.  I lost a lot of time searching/trying to understand how to navigate to my desktop via the command line in Ubuntu only to discover within 30 seconds of the following video that explained where the current file directory is located.

### Suggested Changes

Reverse the order of setting up your environment before Working with files and directories - this will help understand where you are actually working prior to creating the folders and moving things around.

**Comment by lizbur10** [comment]
Hi @mikeship04 ! I have added a reminder to an earlier lesson on how to open the terminal to run bash/zsh commands. Hopefully this will clear up the confusion.

Thanks for contributing to the Flatiron School curriculum 💙
